apiVersion: v1
kind: Namespace
metadata:
  name: pythia
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pythia-data
  namespace: pythia
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests: { storage: 10Gi }
